### ISSUE TITLE
Implement NPCManager

### ISSUE THREAD

**Issue by the-hb** [SzFMV2022-Tavasz/AutomatedCar-A#36]

**Comment by sultgalu** [comment]
Ahogyan megnéztem a kódot egyszerűbbnek tűnik, ha maga az NPC tartalmazza az NPCControllert.
Most NPCEngine-nek neveztem.  

Maga a mozgás a Move()-ban van, és az OnTick() metódus override-olható, így kiegészíthető extra funckiókkal (pl. megáll stop táblánál.)

Az engine példányosításához pont/sebesség tömbökre van csak szükség, azoknak a betöltése külön osztályokban implementálható szerintem
