### ISSUE TITLE
Implement NPC waypoint serializer

### ISSUE THREAD

**Issue by KMate-ISD** [SzFMV2022-Tavasz/AutomatedCar-A#45]
- [x] Add ISerializer interface | #52 
- [x] Add WaypointSerializer class implementing ISerializer | #53 
- [x] WaypointSerializer: Able to deserialize NPC waypoints and corresponding speeds from an appropriately formatted .csv
- [x] WaypointSerializer: Able to serialize NPC waypoints and corresponding speeds into a .csv

**Comment by the-hb** [comment]
Done
